### ISSUE TITLE
PyPlot Broken in Julia 0.5 dev

### ISSUE THREAD

**Issue by dioptre** [stevengj/PyPlot.jl#190] opened 2016-01-19 03:22 UTC
julia> using PyPlot
INFO: Precompiling module PyPlot...
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near /home/a/.julia/v0.5/PyCall/src/PyCall.jl:573
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near /home/a/.julia/v0.5/PyCall/src/PyCall.jl:573
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near /home/a/.julia/v0.5/PyCall/src/PyCall.jl:573
in jl_IO_seek at /home/a/.julia/v0.5/PyCall/src/io.jl
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near /home/a/.julia/v0.5/PyCall/src/PyCall.jl:573
in jl_IO_seek at /home/a/.julia/v0.5/PyCall/src/io.jl
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near /home/a/.julia/v0.5/PyCall/src/PyCall.jl:573
in jl_IO_seek at /home/a/.julia/v0.5/PyCall/src/io.jl
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near /home/a/.julia/v0.5/PyCall/src/PyCall.jl:573
WARNING: Base.FileOffset is deprecated, use Int64 instead.
  likely near /home/a/.julia/v0.5/PyCall/src/PyCall.jl:573
julia-debug: /home/a/julia/src/codegen.cpp:1021: uint64_t getAddressForOrCompileFunction(llvm::Function*): Assertion `addr != 0' failed.

**Comment by ihnorton** [comment] 2016-01-20 22:40
Dup of https://github.com/JuliaLang/julia/issues/14735

**Comment by stevengj** [comment] 2016-02-04 18:15
It works for me now.

**Comment by schmrlng** [comment] 2016-02-06 08:53
Might be a Linux thing, but I still see this error:

```julia
julia> Pkg.checkout("PyCall")
INFO: Checking out PyCall master...
INFO: Pulling PyCall latest master...
INFO: No packages to install, update or remove

julia> Pkg.checkout("PyPlot")
INFO: Checking out PyPlot master...
INFO: Pulling PyPlot latest master...
INFO: No packages to install, update or remove

julia> using PyPlot
INFO: Precompiling module PyPlot...
INFO: Recompiling stale cache file /home/schmrlng/.julia/lib/v0.5/PyCall.ji for module PyCall.
INFO: Recompiling stale cache file /home/schmrlng/.julia/lib/v0.5/Compat.ji for module Compat.
WARNING: Method definition get_splatinfo(Expr, Symbol) in module CompatCartesian at /home/schmrlng/.julia/v0.5/Compat/src/ngenerate.jl:66 overwritten at /home/schmrlng/.julia/v0.5/Compat/src/ngenerate.jl:123.
WARNING: Method definition isfuncexpr(Expr) in module CompatCartesian at /home/schmrlng/.julia/v0.5/Compat/src/ngenerate.jl:106 overwritten at /home/schmrlng/.julia/v0.5/Compat/src/ngenerate.jl:140.
WARNING: Method definition isfuncexpr(Any) in module CompatCartesian at /home/schmrlng/.julia/v0.5/Compat/src/ngenerate.jl:108 overwritten at /home/schmrlng/.julia/v0.5/Compat/src/ngenerate.jl:142.
julia: /home/schmrlng/code/oss/julia-0.5/src/codegen.cpp:1046: uint64_t getAddressForOrCompileFunction(llvm::Function*): Assertion `addr != 0' failed.
ERROR: Failed to precompile PyPlot to /home/schmrlng/.julia/lib/v0.5/PyPlot.ji
 in error(::ASCIIString) at ./error.jl:21
 in compilecache(::ASCIIString) at ./loading.jl:496
 in require(::Symbol) at ./loading.jl:355
 in eval(::Module, ::Any) at ./boot.jl:267

julia> versioninfo()
Julia Version 0.5.0-dev+2507
Commit dbdf28c (2016-02-06 06:47 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1

shell> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

**Comment by stevengj** [comment] 2016-02-06 13:57
Duplicate of JuliaLang/julia#14735

**Closed by stevengj** 2016-02-06 13:57 UTC
