### ISSUE TITLE
Cannot use PyPlot after conda update

### ISSUE THREAD

**Issue by fish830617** [stevengj/PyPlot.jl#186] opened 2016-01-01 20:39 UTC
I use anaconda to install jupyter ect. on my ubuntu.
I just installed julias 0.4.X few days ago and there was no problem using PyPlot.
However, after I update my conda packages today, PyPlot cannot beused;

Here's the command I used to update my packages:
conda update conda
conda update anaconda

Now, in julia,  everytime I call "using PyPlot",
it seems that it cannot find the matplotlib packages;
Julia keeps telling me to install the latest (.15?) one.
But I can import matplotlib in my python code normally......

Julia is really fascinating, I really enjoy its performances.
Can you help solving this problem?

**Comment by stevengj** [comment] 2016-01-05 16:29
Try `Pkg.build("PyCall")` to make sure PyCall's configuration is up to date.

What error message do you get if you type `using PyCall; pyimport("matplotlib")`.

**Comment by fish830617** [comment] 2016-01-05 18:11
Below is the error message I got after `Pkg.build("PyCall")` and then `using PyCall; pyimport("matplotlib")`
***
ERROR: PyError (:PyImport_ImportModule) <class 'ImportError'>
ImportError('/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/linalg/lapack_lite.cpython-34m.so: undefined symbol: zgelsd_',)
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/matplotlib/cbook.py", line 32, in <module>
    import numpy as np
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg

 [inlined code] from /home/chiayufang/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/chiayufang/.julia/v0.4/PyCall/src/PyCall.jl:302
***
***
***
And below is the error message I got after direct `using PyPlot`
***
ERROR: InitError: Failed to pyimport("matplotlib"): PyPlot will not work until you have a functioning matplotlib module.

For automated Matplotlib installation, try configuring PyCall to use the Conda Python distribution within Julia.  Relaunch Julia and run:
      ENV["PYTHON"]=""
      Pkg.build("PyCall")
      using PyPlot

pyimport exception was: PyError (:PyImport_ImportModule) <class 'ImportError'>
ImportError('/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/linalg/lapack_lite.cpython-34m.so: undefined symbol: zgelsd_',)
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/matplotlib/cbook.py", line 32, in <module>
    import numpy as np
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/chiayufang/anaconda3/lib/python3.4/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg

 in __init__ at /home/chiayufang/.julia/v0.4/PyPlot/src/PyPlot.jl:229
 in _require_from_serialized at loading.jl:84
 in require at ./loading.jl:251
during initialization of module PyPlot
***
***
***
But I am sure that `matplotlib` is installed, since after `conda update matplotlib` I got
***
All requested packages already installed.
packages in environment at /home/chiayufang/anaconda3:

matplotlib                1.5.0               np110py34_0
***
Also I can import and plot with matplotlib in python 3 as usual.
I don't understand why....

Hope these information are useful to you and wish this problem can be fixed soon!

**Comment by stevengj** [comment] 2016-02-05 16:03
Duplicate of stevengj/PyCall.jl#65.

Should be fixed by the latest Julia, but you may have to delete some old `openblas` libraries from previous Julia installs.

**Closed by stevengj** 2016-02-05 16:03 UTC
