### ISSUE TITLE
Unable to use PyPlot on a MacBook Pro running Mac OS 10.4.4 with 16 GB of RAM

### ISSUE THREAD

**Issue by ahausknecht** [stevengj/PyPlot.jl#146] opened 2015-07-25 15:42 UTC
Hi,

I am unable to use PyPlot on a MacBook Pro running Mac OS 10.4.4 with 16 GB of RAM.

Here is the error message:
========================
julia> using PyPlot
ERROR: could not open file /Users/ahausknecht/.julia/v0.3/PyCall/src/../deps/deps.jl
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/ahausknecht/.julia/v0.3/PyCall/src/PyCall.jl, in expression starting on line 33
while loading /Users/ahausknecht/.julia/v0.3/PyPlot/src/PyPlot.jl, in expression starting on line 3

**Comment by stevengj** [comment] 2015-07-27 19:59
Duplicate of stevengj/PyCall#174

Please do not post duplicate issues in multiple places.  If you accidentally post an issue in the wrong place, please close the first issue after opening the second one.

**Closed by stevengj** 2015-07-27 19:59 UTC
