### ISSUE TITLE
Using PyPlot fails

### ISSUE THREAD

**Issue by ufechner7** [stevengj/PyPlot.jl#171] opened 2015-09-26 15:24 UTC
Hello,
a new version of the old problem, now with the new miniconda Julia package:
```
julia> using PyPlot
INFO: Recompiling stale cache file /home/ufechner/.julia/lib/v0.4/Conda.ji for module Conda.
INFO: Recompiling stale cache file /home/ufechner/.julia/lib/v0.4/PyPlot.ji for module PyPlot.
INFO: Installing matplotlib via the Conda package...
Fetching package metadata: ........................
Solving package specifications: .
# All requested packages already installed.
# packages in environment at /home/ufechner/.julia/v0.4/Conda/deps/usr:
#
matplotlib                1.4.3                np19py27_2  
ERROR: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('cannot import name scimath',)
  File "/home/ufechner/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/__init__.py", line 180, in <module>
    from matplotlib.cbook import is_string_like
  File "/home/ufechner/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/cbook.py", line 33, in <module>
    import numpy as np
  File "/home/ufechner/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/ufechner/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/ufechner/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath

 [inlined code] from /home/ufechner/.julia/v0.4/PyCall/src/exception.jl:82
 in pyimport at /home/ufechner/.julia/v0.4/PyCall/src/PyCall.jl:321
 in __init__ at /home/ufechner/.julia/v0.4/PyPlot/src/PyPlot.jl:227
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
during initialization of module PyPlot

julia> 
```
Ubuntu 12.04, Julia 0.4rc2

**Comment by stevengj** [comment] 2015-10-01 18:13
Sounds like a duplicate of #140

**Closed by stevengj** 2015-10-01 18:13 UTC
