### ISSUE TITLE
import PyPlot from automated miniconda produces warning+error due to `libpng16.so.16`

### ISSUE THREAD

**Issue by Datseris** [stevengj/PyPlot.jl#229] opened 2016-06-29 08:26 UTC
I installed conda/pycall/pyplot by using the automated procedure:
`ENV["PYTHON"] = ""` 

All the installation was okay. `Pkg.build("PyCall")` works, with message: 
`INFO: Building PyCall
Fetching package metadata .......
Solving package specifications: ..........

All requested packages already installed.
packages in environment at /home/datseris/.julia/v0.4/Conda/deps/usr:
numpy                     1.11.0                   py27_2
INFO: PyCall is using /home/datseris/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.11) at /home/datseris/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/datseris/.julia/v0.4/Conda/deps/usr/lib/libpython2.7.so`

Building `PyPlot` works as well, giving off the same message. Now whether I use `@pyimport matplotlib.pyplot as plt` or `import PyPlot`, I get the same error about some libpng file:

```
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('/home/datseris/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/../../../libpng16.so.16: symbol inflateReset2, version ZLIB_1.2.3.4 not defined in file libz.so.1 with link time reference',)
  File "/home/datseris/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/datseris/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/home/datseris/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/home/datseris/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 62, in <module>
    import matplotlib.textpath as textpath
  File "/home/datseris/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/textpath.py", line 18, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/home/datseris/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/mathtext.py", line 60, in <module>
    import matplotlib._png as _png

 [inlined code] from /home/datseris/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/datseris/.julia/v0.4/PyCall/src/PyCall.jl:79
```

I tried suggestions at a similar thread but it did not work... I am quite confused however about the ending to this library, mainly `.so.16` !

**Comment by stevengj** [comment] 2016-06-29 13:41
Duplicate of #151.

**Closed by stevengj** 2016-06-29 13:41 UTC
