### ISSUE TITLE
Crash on OS X

### ISSUE THREAD

**Issue by crbinz** [stevengj/PyPlot.jl#233] opened 2016-07-24 22:50 UTC
I just updated matplotlib to v1.5.1 via `conda`, and now I get this crash when I try to use PyPlot. I assume it is some issue with a backend, since it does not crash inside an IJulia notebook. I'm using  julia version 0.4.6, with OS X version 10.11.5.

```
julia> using PyPlot
objc[42078]: Class TKApplication is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/cbinz/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[42078]: Class TKMenu is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/cbinz/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[42078]: Class TKContentView is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/cbinz/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[42078]: Class TKWindow is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/cbinz/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
/Users/cbinz/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

julia> plot(rand(5))
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/cbinz/anaconda/lib/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "/Users/cbinz/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 283, in resize
    self.show()
  File "/Users/cbinz/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 355, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/Users/cbinz/anaconda/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
TclError
julia(42078,0x7fff7aa05000) malloc: *** error for object 0x7fd8c515f610: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Abort trap: 6
```

**Comment by stevengj** [comment] 2016-07-24 23:13
Duplicate of #164.

**Closed by stevengj** 2016-07-24 23:13 UTC
