### ISSUE TITLE
Compat issues when adding PyPlot to Julia 0.4.2

### ISSUE THREAD

**Issue by ianshmean** [stevengj/PyPlot.jl#185] opened 2015-12-11 14:52 UTC
A clean install of 0.4.2 allows me to do `using Compat, Requests, DataStructures, JSON` normally, but after I `Pkg.add("PyPlot")` I get the following compat error during install, followed by precompile errors with compat when I try `using Compat, Requests, DataStructures, JSON`

```
Pkg.add("PyPlot")

INFO: Initializing package repository /home/juser/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of ColorTypes from git://github.com/JuliaGraphics/ColorTypes.jl.git
INFO: Cloning cache of Colors from git://github.com/JuliaGraphics/Colors.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Conda from git://github.com/Luthaf/Conda.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of FixedPointNumbers from git://github.com/JeffBezanson/FixedPointNumbers.jl.git
INFO: Cloning cache of JSON from git://github.com/JuliaLang/JSON.jl.git
INFO: Cloning cache of LaTeXStrings from git://github.com/stevengj/LaTeXStrings.jl.git
INFO: Cloning cache of PyCall from git://github.com/stevengj/PyCall.jl.git
INFO: Cloning cache of PyPlot from git://github.com/stevengj/PyPlot.jl.git
INFO: Cloning cache of Reexport from git://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
INFO: Installing BinDeps v0.3.19
INFO: Installing ColorTypes v0.2.0
INFO: Installing Colors v0.6.0
INFO: Installing Compat v0.7.8
INFO: Installing Conda v0.1.8
INFO: Installing Dates v0.4.4
INFO: Installing FixedPointNumbers v0.1.1
INFO: Installing JSON v0.5.0
INFO: Installing LaTeXStrings v0.1.6
INFO: Installing PyCall v1.2.0
INFO: Installing PyPlot v2.1.1
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.1
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Building PyCall
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Compat.ji for module Compat.
===============================[ ERROR: PyCall ]================================

LoadError: unlink: read-only file system (EROFS)
while loading /home/juser/.julia/v0.4/PyCall/deps/build.jl, in expression starting on line 11

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/juser/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
```
---
```
using Compat, Requests, DataStructures, JSON

INFO: Precompiling module Requests...
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/URIParser.ji for module URIParser.
ERROR: LoadError: unlink: read-only file system (EROFS)
 in unlink at fs.jl:102
 in rm at file.jl:59
 in create_expr_cache at loading.jl:330
 in recompile_stale at loading.jl:461
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /opt/julia_packages/.julia/v0.4/Requests/src/Requests.jl, in expression starting on line 11
```

**Comment by stevengj** [comment] 2015-12-11 16:47
Do you have a read-only file system as the error indicates?

**Comment by stevengj** [comment] 2015-12-11 17:00
I'm guessing you are on JuliaBox.   I don't think this has anything to do with PyPlot, but rather is some incompatibility of Julia's caching code with the JuliaBox filesystem.

**Comment by ianshmean** [comment] 2015-12-11 17:06
I am, and thanks for the suggestion. I believe they may be looking into it.

**Comment by stevengj** [comment] 2015-12-11 17:15
Closing as duplicate of abovementioned Julia issue.

**Comment by ianshmean** [comment] 2015-12-11 17:20
Great, thanks for tying the issue together

**Comment by stevengj** [comment] 2016-06-30 18:04
This should now be fixed (see the Julia issue)

**Closed by stevengj** 2016-06-30 18:04 UTC
