### ISSUE TITLE
Incredibly slow plotting for inline figures with IJulia

### ISSUE THREAD

**Issue by mgab** [stevengj/PyPlot.jl#197] opened 2016-03-08 15:20 UTC
When plotting inline figures in a jupyter notebook, it takes a considerable extra amount of time if I do it using the IJulia backend than if I use a GUI backend.
For example:

    using PyPlot
    x = rand(100);
    
    pygui(false)
    tic()
    plt[:hist](x, alpha=0.4, bins=100)
    toc()
     --> elapsed time: 41.750020685 seconds

    pygui(true)
    tic()
    plt[:hist](x, alpha=0.4, bins=100)
    toc()
     --> elapsed time: 0.34994677 seconds

The difference is quite extreme and it becomes unbearable for not so simple plots: 4 overlaid histograms with 100 bins and alpha channel takes a few minutes inline and less than a second the gui backends. Something similar happens with line plots and 3D line plots, that I tried.

It's been a few months since last time I used PyPlot.jl (with Julia 0.3), but it worked fine then.

Versions: julia 0.4.3, updated IJulia and PyPlot packages. python 2.7.10 and matplotlib 1.5.1

Is it a known issue? can anyone reproduce it? If it is a config issue, I'm completely clueless...

Sorry if this issue belongs rather to IJulia, I wasn't sure where to put it.

Thanks!

**Comment by stevengj** [comment] 2016-03-08 15:42
For me I get 0.183017377 seconds with inline plots, and 0.180442986 seconds with the `pygui` plots, so I'm guessing it is something specific to your system?  (I timed each plot twice to avoid any one-time startup cost; for both cases it was around 0.5s for the first plot.)

I have matplotlib 1.4.3 (`PyPlot.version`) and Python 2.7.10 (`PyCall.pyversion`), using the TkAgg backend (`PyPlot.backend`) with Julia 0.4.3 on MacOS X.

**Comment by tbreloff** [comment] 2016-03-08 15:46
I can reproduce this.  I guess the easy answer is... don't call
"pygui(false)"??  My timings were ~32 seconds and ~1 second.

PyPlot.version = v"1.5.0"
PyCall.pyversion = v"2.7.5"
PyPlot.backend = "qt4agg"

**Comment by stevengj** [comment] 2016-03-08 15:52
The default is inline plotting, so `pygui(false)` does nothing unless you call it after `pygui(true)`.

Maybe it is a problem with Matplotlib 1.5?

**Comment by tbreloff** [comment] 2016-03-08 15:54
Correct... if I comment out the "pygui(false)" line, I still see ~32
seconds.  (i.e. it's the *lack* of the pygui(true) that causes the slowdown)

On Tue, Mar 8, 2016 at 10:52 AM, Steven G. Johnson <notifications@github.com

**Comment by stevengj** [comment] 2016-03-08 16:14
Okay, I just switch to Matplotlib 1.5 via Conda, and I can reproduce the problem.  It's still using TkAgg, so the problem is with Matplotlib 1.5.

**Comment by mgab** [comment] 2016-03-11 14:06
Also reproducible with Matplotlib 1.5.0.

On the other hand, both Matplotlib 1.5.1 and 1.5.0 work fine from an IPython kernel, both with the gui mode and the inline mode (with `%matplotlib inline`).

Any idea?

**Comment by stevengj** [comment] 2016-03-11 15:44
I don't see the slowdown if I just `pyimport("matplotlib.pyplot")` manually, either, so something in the way PyPlot is monkey-patching Matplotlib for inline plotting must be going wrong.

**Comment by mgab** [comment] 2016-03-15 14:37
I tried to prune the code in PyPlot.jl to find where is the slow bit.
I ended up with 

    using PyCall
    @pyimport matplotlib as mpl
    mpl.use("Agg")
    mpl.interactive(true)
    @pyimport matplotlib.pyplot as plt

    tic(); plt.hist(rand(100), normed=1, bins=100); toc()
    
It does not plot the figure, but the plotting command already takes a while. 
Setting `mpl.interactive(false)` or changing the backend (I've tried other interactive and non-interactive ones) seems to "solve" the problem. However, running the equivalent code in an IPython kernel takes under a second.

**Comment by maximerischard** [comment] 2016-05-04 13:57
Here's a quick test that might point towards a solution:

```{julia}
using PyPlot
tic()
PyPlot.plt[:interactive](true)
PyPlot.title("interactive=false")
PyPlot.plt[:interactive](false)
PyPlot.plt[:hist](rand(100), normed=1, bins=100);
toc()
```
> elapsed time: 0.22829891 seconds

```{julia}
tic()
PyPlot.plt[:interactive](true)
PyPlot.title("interactive=true")
PyPlot.plt[:hist](rand(100), normed=1, bins=100);
toc()
```
> elapsed time: 8.169930003 seconds

In both these cases, the plot *does* appear in IJulia.

`PyPlot.version=v"1.5.1"`
`PyPlot.plt[:matplotlib][:__version__]="1.5.1"`

**Comment by staticfloat** [comment] 2016-05-20 00:13
I think I'm running into the same issue; I'm trying to plot a 256x1000 matrix, and it's choking PyPlot up.  Here are [my notebooks](https://gist.github.com/staticfloat/d9db1aab5f5ffaaeaab3ad07ec730508) comparing IPython vs. IJulia.  Note that I have to include `PyPlot.plt[:interactive](true)`, otherwise nothing shows up in my notebooks.

**Comment by marius311** [comment] 2016-06-07 11:28
I confirm the issue with matplotlib 1.5.1 and that it goes away upon downgrading to 1.4.3. Any hope for a fix and/or better workarounds?

**Comment by tbreloff** [comment] 2016-06-07 14:00
~~I think this might be related to svg output?  Is there a `svg(false)` command?~~  That doesn't see to help?

The other option is to use PyPlot through Plots.  I recently "fixed" this issue by changing the default output format to PNG for PyPlot.

![tmp](https://cloud.githubusercontent.com/assets/933338/15860258/44cdfd90-2c96-11e6-9f05-3063316a0737.png)

**Comment by stevengj** [comment] 2016-06-07 14:47
@tbreloff, the default output format for PyPlot in IJulia is already PNG.

I just tried this again on my machine, with Matplotlib 1.5.1 from IJulia, and I'm not seeing any slowdown.

**Comment by stevengj** [comment] 2016-06-07 14:49
Oh wait, I was just using `plot(rand(100))`.  This seems fine.  But I'm seeing the `hist` slowdown.

**Comment by stevengj** [comment] 2016-06-07 14:55
I've checked, and it is never calling `writemime` for SVG output.

**Comment by stevengj** [comment] 2016-06-07 14:57
@tbreloff, I'm confused by your comment; what exactly did you change to PNG to fix it?   As far as I can tell, IJulia is already using PNG with PyPlot.

**Comment by tbreloff** [comment] 2016-06-07 15:13
The code: https://github.com/tbreloff/Plots.jl/blob/master/src/output.jl#L125-L194.  If you notice any glaring mistakes with how I've approached this, please let me know.  It was a little trial and error to get things working.

**Comment by stevengj** [comment] 2016-06-07 16:32
It looks like the problem has to do with enabling `interactive` mode in Matplotlib with a switched backend.  I think in Plots.jl you use `matplotlib.interactive(false)`?

**Comment by tbreloff** [comment] 2016-06-07 16:36
Yes I do call `PyPlot.ioff()` during initialization, and I explicitly call draw/show methods.

**Comment by stevengj** [comment] 2016-06-07 17:46
Okay, hopefully this is fixed in PyPlot `master`.

**Closed** 2016-06-07 17:46 UTC

**Comment by marius311** [comment] 2016-06-07 17:51
That fixed it for me. Thanks!
