### ISSUE TITLE
figures not showing in IJulia

### ISSUE THREAD

**Issue by axsk** [stevengj/PyPlot.jl#118] opened 2015-03-02 15:46 UTC
![image](https://cloud.githubusercontent.com/assets/5798790/6444041/4aaed070-c0fb-11e4-9d48-ec5392d15e3f.png)

Ran into this problem about two weeks ago, and it still persists with newest Julia nightly and Pkg.update(). (Gadfly plots are working..)
Is there anyone else who can confirm this?

Here the code:
``` julia
using PyPlot
x = linspace(0,2*pi,1000)
y = sin(3*x + 4*cos(2*x));
plot(x, y, color="red", linewidth=2.0, linestyle="--")
```

**Comment by stevengj** [comment] 2015-03-02 17:16
I just ran into this myself.  On my laptop, I got rid of it by deleting the `~/.julia` directory and re-installing the packages, but now I ran into it on my other machine too; I'm not sure what is going on yet.

**Comment by axsk** [comment] 2015-03-02 18:11
I am using 32bit-Julia on Windows8.

**Comment by stevengj** [comment] 2015-03-02 22:16
The error seems related to PNG (binary image) output, as SVG (text) output works (do `PyPlot.svg(true)`)

**Comment by stevengj** [comment] 2015-03-02 22:41
It seems to come from stevengj/PyCall.jl@183c915804ae470cb0a6acff123551dd27dde43d ... reverting this patch fixes the problem (on Python 2).  I think that the problem is that on Python 2 it is trying to convert binary data to a UTF-8 string and getting confused by the encoding.

**Comment by stevengj** [comment] 2015-03-03 18:30
Should be fixed by the latest PyCall version.

**Closed** 2015-03-03 18:29 UTC
Labels: bug

**Comment by axsk** [comment] 2015-03-25 13:52
Although late, thank you!
It's working :)
