### ISSUE TITLE
Init Error when doing: using PyPlot

### ISSUE THREAD

**Issue by spiralizing** [stevengj/PyPlot.jl#177] opened 2015-10-26 18:44 UTC
While trying to use PyPlot in Julia I'm getting this error:
https://gist.github.com/spiralizing/a84fcef28ef6f68c4894#file-gistfile1-txt

Any ideas?

**Comment by stevengj** [comment] 2015-10-27 02:10
Sounds like a duplicate of stevengj/PyCall.jl#65.    Use Julia 0.4, and make sure you don't have an old `libopenblas.so` file lying around.

**Closed by stevengj** 2015-10-27 02:10 UTC
