### ISSUE TITLE
Failed to precompile PyPlot

### ISSUE THREAD

**Issue by berceanu** [stevengj/PyPlot.jl#216] opened 2016-05-25 13:10 UTC
```
julia> using PyPlot
INFO: Precompiling module PyPlot...
ERROR: LoadError: InitError: cfunction: pyjlwrap_repr does not return
 in __init__ at /home/berceanu/.julia/v0.4/PyCall/src/pyinit.jl:88
 in _require_from_serialized at loading.jl:84
 [inlined code] from none:2
 in anonymous at no file:0
during initialization of module PyCall
while loading /home/berceanu/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: Failed to precompile PyPlot to /home/berceanu/.julia/lib/v0.4/PyPlot.ji
 in compilecache at loading.jl:400
```

```
julia> versioninfo(true)
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  uname: Linux 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 unknown
Memory: 7.695919036865234 GB (3657.3984375 MB free)
Uptime: 10152.0 sec
Load Avg:  1.14111328125  1.22021484375  1.30322265625
Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz: 
       speed         user         nice          sys         idle          irq
#1  2654 MHz      25606 s         79 s       6134 s     736544 s          0 s
#2  2690 MHz      29798 s          0 s       5117 s     421620 s          0 s
#3  2400 MHz      24801 s          1 s       7117 s     419335 s          0 s
#4  2400 MHz      30778 s          0 s       4704 s     420576 s          0 s

  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.3
Environment:
  HOME = /home/berceanu
  MOZ_PLUGIN_PATH = /usr/lib/mozilla/plugins
  PATH = /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/berceanu/.cabal/bin:/home/berceanu/bin
  TERM = screen-256color
  WINDOWPATH = 1

Package Directory: /home/berceanu/.julia/v0.4
1 required packages:
 - PyPlot                        2.1.1
13 additional packages:
 - BinDeps                       0.3.21
 - ColorTypes                    0.2.2
 - Colors                        0.6.4
 - Compat                        0.7.19
 - Conda                         0.2.0
 - FixedPointNumbers             0.1.3
 - JSON                          0.5.0
 - LaTeXStrings                  0.1.6
 - MacroTools                    0.3.0
 - PyCall                        1.6.1
 - Reexport                      0.0.3
 - SHA                           0.1.2
 - URIParser                     0.1.3
```

```
julia> Pkg.build("PyCall")
INFO: Building PyCall
Fetching package metadata: ....
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /home/berceanu/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.11.0                   py27_1  
INFO: PyCall is using /home/berceanu/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.11) at /home/berceanu/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/berceanu/.julia/v0.4/Conda/deps/usr/lib/libpython2.7.so
```

I also tried using `Python 3.5.1` installed via `pacman`, but I get the same error as above.

**Comment by stevengj** [comment] 2016-05-25 16:25
This is a duplicate of stevengj/PyCall.jl#281 ... it is actually a bug in Compat.jl (JuliaLang/Compat.jl#210) and is fixed by JuliaLang/Compat.jl#211

**Closed by stevengj** 2016-05-25 16:25 UTC

**Comment by diegozea** [comment] 2016-05-25 20:48
I had the same problem, `Pkg.checkout("Compat")` solved it ;)
