### ISSUE TITLE
compile error using Julia 0.5

### ISSUE THREAD

**Issue by jingpengwu** [stevengj/PyPlot.jl#204] opened 2016-04-05 14:50 UTC
everything works great in Julia 0.4, but when I try to use it in Julia 0.5. I get the following error:
Ubuntu 14.10, python 2.7
```
julia> Pkg.build("PyPlot")
INFO: Building PyCall
WARNING: readall is deprecated, use readstring instead.
 [inlined code] from ./error.jl:26
 in depwarn(::ASCIIString, ::Symbol) at ./deprecated.jl:64
 [inlined code] from ./strings/io.jl:53
 in readall(::Cmd, ::Vararg{Cmd}) at ./deprecated.jl:30
 in (::__anon__.#pyconfigvar#3)(::ASCIIString, ::ASCIIString) at /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl:25
 in (::__anon__.#pyconfigvar#3)(::ASCIIString, ::ASCIIString, ::ASCIIString) at /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl:26
 [inlined code] from /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl:126
 in anonymous at ./<no file>:4294967295
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in eval(::Module, ::Any) at ./boot.jl:237
 [inlined code] from ./sysimg.jl:11
 in evalfile(::ASCIIString, ::Array{UTF8String,1}) at ./loading.jl:433 (repeats 2 times)
 in cd(::##2#4, ::ASCIIString) at ./file.jl:48
 in (::##1#3)(::IOStream) at ./none:13
 in open(::##1#3, ::ASCIIString, ::ASCIIString) at ./iostream.jl:114
 in eval(::Module, ::Any) at ./boot.jl:237
 [inlined code] from ./sysimg.jl:11
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
WARNING: readall is deprecated, use readstring instead.
 [inlined code] from ./error.jl:26
 in depwarn(::ASCIIString, ::Symbol) at ./deprecated.jl:64
 [inlined code] from ./strings/io.jl:53
 in readall(::Cmd, ::Vararg{Cmd}) at ./deprecated.jl:30
 in (::__anon__.#pysys#4)(::ASCIIString, ::ASCIIString) at /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl:30
 in (::__anon__.#find_libpython#5)(::ASCIIString) at /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl:48
 [inlined code] from /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl:143
 in anonymous at ./<no file>:4294967295
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in eval(::Module, ::Any) at ./boot.jl:237
 [inlined code] from ./sysimg.jl:11
 in evalfile(::ASCIIString, ::Array{UTF8String,1}) at ./loading.jl:433 (repeats 2 times)
 in cd(::##2#4, ::ASCIIString) at ./file.jl:48
 in (::##1#3)(::IOStream) at ./none:13
 in open(::##1#3, ::ASCIIString, ::ASCIIString) at ./iostream.jl:114
 in eval(::Module, ::Any) at ./boot.jl:237
 [inlined code] from ./sysimg.jl:11
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /usr/people/jingpeng/.julia/v0.5/PyCall/deps/build.jl, in expression starting on line 17
INFO: PyCall is using /usr/bin/python (Python 2.7.10) at /usr/bin/python, libpython = libpython2.7
```
```
julia> using PyPlot
INFO: Precompiling module PyPlot...
INFO: Recompiling stale cache file /usr/people/jingpeng/.julia/lib/v0.5/PyCall.ji for module PyCall.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
ERROR: Failed to precompile PyPlot to /usr/people/jingpeng/.julia/lib/v0.5/PyPlot.ji
 in error(::ASCIIString) at ./error.jl:21
 in compilecache(::ASCIIString) at ./loading.jl:496
 in compilecache(::Symbol) at ./loading.jl:485
 in require(::Symbol) at ./loading.jl:355
 in eval(::Module, ::Any) at ./boot.jl:237

```

**Comment by stevengj** [comment] 2016-04-06 16:37
It sounds like the problem is with PyCall, not PyPlot?   You should try to get
```
Pkg.build("PyCall")
using PyCall
```
working first...

Note that there have been some recent problems with PyCall on Julia 0.5 (see stevengj/PyCall.jl#254), although maybe they have been fixed with the most recent Julia master.

**Closed by stevengj** 2016-04-06 16:37 UTC
